const actions = {
  LOGIN_START: "LOGIN_START",
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  RESTART: "RESTART",
};
export default actions;
